### ISSUE TITLE
Icon request: Kodi

### ISSUE THREAD

**Issue by MichaelTiebesl** [hayderctee/masalla-icon-theme#1]
Is it possible to have an icon for Kodi?

[Desktop Entry]
Version=1.0
Name=Kodi Media Center
GenericName=Media Center
Comment=Manage and view your media
Exec=kodi
Icon=kodi
Terminal=false
Type=Application
Categories=AudioVideo;Video;Player;TV;

Actions=Fullscreen;Standalone;

[Desktop Action Fullscreen]
Name=Open in fullscreen
Exec=kodi -fs
OnlyShowIn=Unity;

[Desktop Action Standalone]
Name=Open in standalone mode
Exec=kodi --standalone
OnlyShowIn=Unity;

![kodi](https://cloud.githubusercontent.com/assets/10792019/8922083/f3dde1f2-3510-11e5-91ab-75cde01dd9f0.png)

**Comment by hayderctee** [comment]
you will see it in next version

**Comment by MichaelTiebesl** [comment]
Thanks

**Comment by MichaelTiebesl** [comment]
I already made the icon for kodi. svg and png

![kodi48](https://cloud.githubusercontent.com/assets/10792019/10557406/f2149b74-74dd-11e5-8425-490dce9bd5f5.png)

**Comment by hayderctee** [comment]
Just like my icon 0_o 
Thanks alooooooot for your support bro , thanks

**Comment by hayderctee** [comment]
I will use your icon ^_^ it's so beautiful
