### ISSUE TITLE
Ubuntu 16.10 - issue with `input-keyboard.svg`

### ISSUE THREAD

**Issue by mbacou** [hayderctee/masalla-icon-theme#10]
Hi,
Just installed the latest branch on a Ubuntu 16.10, looks excellent but I have 1 odd missing icon for the `im-config` app (Set Keyboard Input Method). I can see the SVG file `input-keyboard.svg` in the masalla archive so not sure what's wrong.
Thanks!

![image](https://cloud.githubusercontent.com/assets/260325/23693335/f7ff1d3a-03a1-11e7-8cf6-9e452c4b02cb.png)

**Comment by hayderctee** [comment]
Hi
What is your DE you use ?

**Comment by mbacou** [comment]
Using GNOME Shell 3.20.4. But I think it's fixed now (else I might have fixed it myself, can't recall (-:

![image](https://user-images.githubusercontent.com/260325/28749528-9ce39df0-7498-11e7-982c-0e32facea098.png)

**Comment by hayderctee** [comment]
That's great :+1: 
I’m using the same version of gnome and it's working fine in my laptop with the latest version :)
