### ISSUE TITLE
  Icon request: MusicBrainz Picard

### ISSUE THREAD

**Issue by MichaelTiebesl** [hayderctee/masalla-icon-theme#2]
Is it possible to have an icon for MusicBrainz Picard?

[Desktop Entry]
Name=MusicBrainz Picard
Comment=Tag your music with the next generation MusicBrainz tagger
Exec=picard %F
Terminal=false
Type=Application
StartupNotify=true
Icon=picard
Categories=AudioVideo;Audio;AudioVideoEditing;
MimeType=audio/x-mp3;audio/ogg;audio/mpeg;application/ogg;audio/x-flac;audio/x-flac+ogg;audio/x-vorbis+ogg;audio/x-speex+ogg;audio/x-oggflac;audio/x-musepack;audio/x-tta;audio/x-ms-wma;audio/x-wavpack;

![picard](https://cloud.githubusercontent.com/assets/10792019/8922184/529c86fc-3512-11e5-859a-8ab87b139724.png)

**Comment by hayderctee** [comment]
you will see it in next version

**Comment by MichaelTiebesl** [comment]
Thanks

**Comment by MichaelTiebesl** [comment]
I already made the icon for picard. svg and png

![picard48](https://cloud.githubusercontent.com/assets/10792019/10557407/02785ea6-74de-11e5-8f56-53ce9def10af.png)

**Comment by hayderctee** [comment]
Nice icon :) , but I already made icon too ^_^
