### ISSUE TITLE
Symlinks point to non-existing

### ISSUE THREAD

**Issue by MichaelTiebesl** [hayderctee/masalla-icon-theme#4]
Hey hello,
Almost done with the AUR.
This is what i found when i make an PKGBUILD for the AUR.
Maybe you can do something with this info:

https://paste.gnome.org/p9ilol43z

New icons looks great!!

**Comment by hayderctee** [comment]
Just delete the fake links and i will fix it in new version (with the black theme :) )
Thanks for your great help and advice, thanks a lot :)
