### ISSUE TITLE
Masalla in AUR and few questions.

### ISSUE THREAD

**Issue by MichaelTiebesl** [hayderctee/masalla-icon-theme#6]
Hi there,

I just finished the AUR. (_PPA will follow soon_) I have tested i it is working okay.
See: https://aur.archlinux.org/packages/masalla-icon-theme/
People can get it by: yaourt masalla-icon-theme

I also see that you have to update READ.ME
I see there is an dot missing after _language_ in "arabic language
Icons are licensed "

Also i mention in PKGBUILD from AUR this: Latest flat design theme by Hayder Majid
Is that correct the name Hayer Majid?

Version i made 0.8 is that correct?

Last thing is that i name it Masalla in usr/share/icons/Masalla and not usr/share/icons/masalla-icon-theme
So people will have /usr/share/icons/Masalla then.
How is that? I found it better to call it Masalla.

This you can ad to READ.ME if you want:
#### Arch

Arch users can install this community maintained [AUR package](https://aur.archlinux.org/packages/masalla-icon-theme/).

Cheers

**Comment by hayderctee** [comment]
can we contact by emails ? ^_^

**Comment by MichaelTiebesl** [comment]
Sure

**Comment by hayderctee** [comment]
I will make the PPA and .deb package :)
BIG THANX TO YOU MY FRIEND ^^ 
THANX
