### ISSUE TITLE
Missing icons in Ubuntu Mate

### ISSUE THREAD

**Issue by rapic-dev** [hayderctee/masalla-icon-theme#7]
Hello! First of all thank you for the **fantastic** icon theme! I came across some missing icons in Ubuntu Mate 16.04. Two icons are missing in the Caja file manager, the icon for "Preferences" under the "Edit" menu and for "Contents" under the "Help" menu. One more icon is missing on the "Panel" right click menu for "Help".

Here is the screenshot album with the missing icons: https://imgur.com/a/uUC56

Cheers!

**Comment by hayderctee** [comment]
The problem has been resolved in this version (0.9)  :+1:  
Have fun and be free :)
