### ISSUE TITLE
please add an icon for spyder (python editor)

### ISSUE THREAD

**Issue by nonamedotc** [hayderctee/masalla-icon-theme#9]
Spyder is a popular editor for python. Can you please add an icon for that?

Here are some examples - 

![spyder_square2_icon_theme](https://cloud.githubusercontent.com/assets/1994161/23687564/172717a0-037d-11e7-882b-4a91c895b5ea.png)
![spyder_vivacious](https://cloud.githubusercontent.com/assets/1994161/23687563/1723a3d6-037d-11e7-86a3-ed445dc3b176.png)

Thanks for a great icon theme!

**Comment by mbacou** [comment]
A few other missing app icons (more for scientists) in case someone knows how to make these:

Jupyter Notebook (exec: `jupyter`)

![image](https://cloud.githubusercontent.com/assets/260325/23693661/954e52e4-03a3-11e7-9871-d0a51a42c4bc.png)

Beaker Notebook (exec: `beaker`)

![image](https://cloud.githubusercontent.com/assets/260325/23693693/c2879f36-03a3-11e7-91ff-2afc568b462a.png)

http://beakernotebook.com/ 

GRASS GIS (exec: `grass70`)

![image](https://cloud.githubusercontent.com/assets/260325/23693557/ee7c8116-03a2-11e7-86f2-18bbd682ae21.png)

QGIS Browser (part of the QGIS suite) (exec: `qbrowser`)

![image](https://cloud.githubusercontent.com/assets/260325/23693547/e435bdf8-03a2-11e7-84d0-731a864e082c.png)

Neo4J Graph Database (exec: `neo4j`)

![image](https://cloud.githubusercontent.com/assets/260325/23693621/52b98f3e-03a3-11e7-83c1-80f2848c0e42.png)

**Comment by hayderctee** [comment]
Done :+1:

**Comment by mbacou** [comment]
Thanks! Great job, it's a wonderful icon set. After updating I do get the same issue as earlier with my input-method icon though (might be a glitch in Ubuntu 16.10):

![image](https://user-images.githubusercontent.com/260325/29198291-927a704c-7e10-11e7-9282-7d5f87208b57.png)

**Comment by mbacou** [comment]
I have few other missing ones to suggest for fairly common Linux applications:

**STATA**
http://www.stata.com/ 
<img src="https://user-images.githubusercontent.com/260325/29198542-fcf662ee-7e12-11e7-8280-9a9773ca54a8.png" width="150px" />

**Feedly**
https://feedly.com/
<img src="https://user-images.githubusercontent.com/260325/29198532-e5028de8-7e12-11e7-91a2-b579117b32e0.png" width="150px" />

**Grsync**
http://www.opbyte.it/grsync/
<img src="https://user-images.githubusercontent.com/260325/29198523-c2f185d8-7e12-11e7-9375-f83c9b6bcd2c.png" width="150px" />

**overGrive** (Google Drive sync client) 
https://www.thefanclub.co.za/overgrive 
<img src="https://user-images.githubusercontent.com/260325/29198517-adee1c5a-7e12-11e7-9337-73b4e1479bf3.png" width="150px" />

**Pithos**
https://pithos.github.io/
<img src="https://user-images.githubusercontent.com/260325/29198629-c5b714bc-7e13-11e7-859f-6207e608b118.png" width="150px" />

**Comment by nonamedotc** [comment]
@hayderctee Thank you!
